version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1111
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      # host.docker.internal
      - '5432:5432'
volumes:
  postgres: